### ISSUE TITLE
❓ will this work server sided?

### ISSUE THREAD

**Issue by synxs-91** [ceko/valheim-armorstand#1]
To run this on a dedicated server does the mod need to be installed server side?
or just on 1 client?

**Comment by ceko** [comment]
The way the mod currently works, if everyone does not have it (including the server) the armor stand could disappear with all your items. That's because the server removes all invalid items on startup, and if it doesn't have my mod, it will mark the armor stand as invalid.

I'm working on a way to guard against that, but Irongate's base code isn't friendly to custom pieces and items.

At the very least the server needs it to survive restarts.

**Comment by synxs-91** [comment]
brilliant if i install on server and someone joins without. will it delete for them or will they just not see the item ?

**Comment by ceko** [comment]
It shouldn't delete it. I did some additional testing and found a dedicated server does not need the mod either. My stand survived several restarts without being cleaned up.

It's still safest to install it on the server as well if possible, in case I missed something or Valheim changes in the future. My host doesnt allow that so I can't test. 

Player hosted servers absolutely need the mod though.

Keep me posted on how it works.
